spec:
  template:
    spec:
      containers:
      - name: athenz-zts-server
        volumeMounts:
        - name: providers-json-vol
          mountPath: /opt/athenz/zts/conf/providers.json
          subPath: providers.json
      volumes:
      - name: providers-json-vol
        configMap:
          name: zts-providers-config
