version: 1
servers:
  confluence:
    defaultPermission: none
    tools: {}
  k8s-docs-server:
    tools:
      get_k8s_docs:
        requirements:
        - label: Signed-in user can call GET /api/docs
          member: <signed_in_user>
          role: api:role.docs-getter
        - label: MCP Gateway can request an ID-JAG exchange for GET /api/docs on behalf of the signed-in user
          member: mcp-hub.mcp-gateway
          role: api:role.docs-getter-jag-exchanger
        - label: K8s Docs MCP server can exchange an AT for GET /api/docs access
          member: api.api-mcp
          role: api:role.docs-getter-exchanger
      post_k8s_doc:
        requirements:
        - label: Signed-in user can call POST /api/docs
          member: <signed_in_user>
          role: api:role.docs-poster
        - label: MCP Gateway can request an ID-JAG exchange for POST /api/docs on behalf of the signed-in user
          member: mcp-hub.mcp-gateway
          role: api:role.docs-poster-jag-exchanger
        - label: K8s Docs MCP server can exchange an AT for POST /api/docs access
          member: api.api-mcp
          role: api:role.docs-poster-exchanger
      delete_k8s_doc:
        requirements:
        - label: Signed-in user can call DELETE /api/docs/{doc_id}
          member: <signed_in_user>
          role: api:role.docs-deleter
        - label: MCP Gateway can request an ID-JAG exchange for DELETE /api/docs/{doc_id} on behalf of the signed-in user
          member: mcp-hub.mcp-gateway
          role: api:role.docs-deleter-jag-exchanger
        - label: K8s Docs MCP server can exchange an AT for DELETE /api/docs/{doc_id} access
          member: api.api-mcp
          role: api:role.docs-deleter-exchanger
