# This workflow creates a docker image that pushes the jar file
# For more details, check out the markdown file under the same directory of this yml.

name: Build and Push KeycloakTokenExchangeProvider JAR file

on:
  push:
    branches: [ "main" ]
    paths:
      - "components/keycloak_token_exchange_provider/**"
      - ".github/workflows/publish-keycloak-token-exchange-provider.yml"
      - ".github/workflows/build-multiarch-image.yml"
      - ".github/scripts/check-container.sh"

  pull_request:
    branches: [ "main" ]
    paths:
      - "components/keycloak_token_exchange_provider/**"
      - ".github/workflows/publish-keycloak-token-exchange-provider.yml"
      - ".github/workflows/build-multiarch-image.yml"
      - ".github/scripts/check-container.sh"

  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    uses: ./.github/workflows/build-multiarch-image.yml
    with:
      image: keycloak-token-exchange-provider
      context: ./components/keycloak_token_exchange_provider
      java-build: |
        mvn -B clean package -DskipTests
        mv target/original-keycloak-token-provider-*.jar target/plugin-latest.jar
    secrets:
      DEPLOY_GHCR_SECRET: ${{ secrets.DEPLOY_GHCR_SECRET }}
