name: Build and Push ZPU Image

on:
  push:
    branches: [ "main" ]
    paths:
      - "zpu/**"
      - ".github/workflows/publish-zpu.yml"
      - ".github/workflows/build-multiarch-image.yml"
      - ".github/scripts/check-container.sh"
  pull_request:
    branches: [ "main" ]
    paths:
      - "zpu/**"
      - ".github/workflows/publish-zpu.yml"
      - ".github/workflows/build-multiarch-image.yml"
      - ".github/scripts/check-container.sh"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    uses: ./.github/workflows/build-multiarch-image.yml
    with:
      image: zpu
      context: ./zpu
    secrets:
      DEPLOY_GHCR_SECRET: ${{ secrets.DEPLOY_GHCR_SECRET }}
