#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PORT="$SCRIPT_DIR/../../tools/port.sh"
ATHENZD_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$ATHENZD_DIR/.athenzd/config.yaml"

ZTS=$("$PORT" zts)
ZMS=$("$PORT" zms)
KEYCLOAK=$("$PORT" keycloak-https)
# The local Keycloak HTTPS cert is signed by the Athenz tutorial CA, so athenzd
# must trust that CA to complete the token exchange over the keycloak.idp host
# mapped to the local Keycloak HTTPS port-forward.
CA="$(cd "$ATHENZD_DIR/.." && pwd)/athenz_dist/certs/ca.cert.pem"

mkdir -p "$(dirname "$OUT")"

# The project config is what athenzd reads first (./.athenzd/config.yaml). Don't
# clobber an existing one without consent. FORCE=1 skips the prompt (used by CI
# and `make test`, which cannot answer an interactive question).
if [ -f "$OUT" ] && [ "${FORCE:-}" != "1" ]; then
  printf "Overwrite existing project config %s? [y/N] " "$OUT" >&2
  read -r reply
  case "$reply" in
    y | Y | yes | YES) ;;
    *)
      echo "Kept existing config — not overwritten." >&2
      cat "$OUT"
      exit 0
      ;;
  esac
fi

cat > "$OUT" <<EOF
# Generated by hack/gen-idjag-learner-config.sh — do not edit. Run make idjag-learner to regenerate.

athenz:
  zts: https://localhost:${ZTS}/zts/v1
  zms: https://localhost:${ZMS}/zms/v1

current_service: idjag-learner

services:
  - name: idjag-learner
    athenz:
      domain: home.mlajkim
      provider: sys.auth.zts
    idp:
      issuer: https://keycloak.idp:${KEYCLOAK}/realms/master
      client_id: athenzd
      callback_port: 8250
      ca_file: ${CA}
EOF

# Validate silently — a broken config still fails the build (set -e), but on
# success the only output is the generated config itself.
go run "$ATHENZD_DIR/cmd/athenzd" config validate -f "$OUT" >/dev/null 2>&1

cat "$OUT"
