#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PORT="$SCRIPT_DIR/../../tools/port.sh"
ATHENZD_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$ATHENZD_DIR/athenzd.idjag-learner.yaml"

ZTS=$("$PORT" zts)
ZMS=$("$PORT" zms)

cat > "$OUT" <<EOF
# Generated by hack/gen-idjag-learner-config.sh — do not edit. Run make idjag-learner to regenerate.

athenz:
  zts: https://localhost:${ZTS}/zts/v1
  zms: https://localhost:${ZMS}/zms/v1

current_service: idjag-learner

services:
  - name: idjag-learner
    athenz:
      domain: home.mlajkim
      provider: sys.auth.zts
EOF

echo "Generated athenzd.idjag-learner.yaml (ZTS=${ZTS}, ZMS=${ZMS})"

validate() {
  echo "Validating with: go run ./cmd/athenzd config validate -f $OUT"
  go run "$ATHENZD_DIR/cmd/athenzd" config validate -f "$OUT"
}

validate

echo ""
echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║  ⚠  ACTION REQUIRED: edit this script before committing             ║"
echo "║                                                                      ║"
echo "║  hack/gen-idjag-learner-config.sh still has placeholder values:     ║"
echo "║    domain:   home.mlajkim   → replace with your Athenz home domain  ║"
echo "║    provider: sys.auth.zts   → replace with your identity provider   ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
