#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PORT="$SCRIPT_DIR/../../tools/port.sh"
ATHENZD_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$ATHENZD_DIR/.athenzd/config.yaml"

ZTS=$("$PORT" zts)
ZMS=$("$PORT" zms)
KEYCLOAK=$("$PORT" keycloak-https)
# The local Keycloak HTTPS cert is signed by the Athenz tutorial CA, so athenzd
# must trust that CA to complete the token exchange over the keycloak.idp host
# mapped to the local Keycloak HTTPS port-forward.
CA="$(cd "$ATHENZD_DIR/.." && pwd)/athenz_dist/certs/ca.cert.pem"

mkdir -p "$(dirname "$OUT")"

# The project config is what athenzd reads first (./.athenzd/config.yaml). Don't
# clobber an existing one without consent.
if [ -f "$OUT" ]; then
  printf "Overwrite existing project config %s? [y/N] " "$OUT" >&2
  read -r reply
  case "$reply" in
    y | Y | yes | YES) ;;
    *)
      echo "Kept existing config — not overwritten." >&2
      cat "$OUT"
      exit 0
      ;;
  esac
fi

cat > "$OUT" <<EOF
# Generated by hack/gen-idjag-learner-config.sh — do not edit. Run make idjag-learner to regenerate.

athenz:
  zts: https://localhost:${ZTS}/zts/v1
  zms: https://localhost:${ZMS}/zms/v1
  ca_file: ${CA}

current_service: idjag-learner

gen_ai:
  domain: gen-ai.services.{{project}}
  role: gen-ai-users

services:
  - name: idjag-learner
    athenz:
      service: home.{{.preferred_username}}.local.athenzd
      optional_admins:
        - user.athenz_admin
      provider: sys.auth.localworkload
    idp:
      issuer: https://keycloak.idp:${KEYCLOAK}/realms/master
      client_id: athenzd
      callback_port: 8250
      ca_file: ${CA}
    identity:
      mode: copperargos
      instance_id: idjag-learner-athenzd
      cert_file: ~/.config/athenzd/identity/idjag-learner.cert.pem
      key_file: ~/.config/athenzd/identity/idjag-learner.key.pem
      ca_file: ~/.config/athenzd/identity/ca.cert.pem
      expiry_minutes: 60
EOF

# Validate silently — a broken config still fails the build (set -e), but on
# success the only output is the generated config itself.
go run "$ATHENZD_DIR/cmd/athenzd" config validate -f "$OUT" >/dev/null 2>&1

cat "$OUT"
